name: Run Gradle, build, test, publish snapshot
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
      - name: Test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test
      - name: Publish
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.CI_PUBLISH }}
